baseURL = "https://wuhoo.xyz/"
languageCode = "en"
defaultContentLanguage = "en"

title = "wuhoo!"

enableEmoji = false
disableKinds = ["taxonomy", "term"]

[author]
name = "wuhoo!"
image = "img/author.webp" # path relative to static directory

links = [
  { authentik = { href = "https://auth.wuhoo.xyz", text = "Authentik" } },
  { nextcloud = { href = "https://cloud.wuhoo.xyz", text = "Nextcloud" } },
  { gitlab = { href = "https://gitlab.wuhoo.xyz/explore/", text = "GitLab" } },
  { jellyfin = { href = "https://jellyfin.wuhoo.xyz", text = "Jellyfin" } },
  { bitwarden = { href = "https://vaultwarden.wuhoo.xyz", text = "Vaultwarden" } },
  { send = { href = "https://send.wuhoo.xyz", text = "Send" } },
  { privatebin = { href = "https://paste.wuhoo.xyz", icon = "", text = "Privatebin" } },
  { wallabag = { href = "https://wallabag.wuhoo.xyz", icon = "", text = "Wallabag" } },
  { uptimekuma = { href = "https://uptime.wuhoo.xyz/status/services", text = "Status" } },
]

[module]
[module.hugoVersion]
extended = false
min = "0.86.1"
